### ISSUE TITLE
how is the p[assword of docker image?

### ISSUE THREAD

**Issue by huge818** [sjitech/build-nodejs-for-android-perfectly#5]

**Comment by huge818** [comment]
osexp2000/build-nodejs-for-android

**Comment by huge818** [comment]
how is the password of docker image?

**Comment by jjqq2013** [comment]
Sorry i did not mention that because i think that is a convension about docker image usage.

You do not need use password to access my private docker hub page.

Please run

"docker run osexp2000/build-nodejs-for-android"

Then you will will be automatically dowliad the image for the first time.

**Comment by jjqq2013** [comment]
Sorry i did not mention that because i think that is a convension about docker image usage.

You do not need use password to access my private docker hub page.

Please run

"docker run osexp2000/build-nodejs-for-android"

Then you will will be automatically dowliad the image for the first time.

**Comment by DerGoogler** [comment]
not work
